"""products reviews

Revision ID: 0d968028955c
Revises: e2141bc01491
Create Date: 2024-09-19 04:32:52.052126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d968028955c'
down_revision: Union[str, None] = 'e2141bc01491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_review',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_products_review_customer_id_customers')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_products_review_product_id_products')),
    sa.PrimaryKeyConstraint('product_id', 'customer_id', name=op.f('pk_products_review'))
    )
    with op.batch_alter_table('products_review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_review_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products_review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_review_timestamp'))

    op.drop_table('products_review')
    # ### end Alembic commands ###
